apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: myapp
        image: 645026774230.dkr.ecr.ca-central-1.amazonaws.com/k8s-workshop-app1:<your_tag>
        resources:
          limits:
            memory: "30Mi"
            cpu: "10m"
        ports:
        - containerPort: 3000
        env:
          - name: TIME_SERVICE_API
            value: http://time-service/current-time

